                cloud_id: 14
               available: Y
                    name: Eucalyptus Partner Cloud
                delegate: org.dasein.cloud.euca.Eucalyptus
      supports_addresses: Y
                   owner: NULL
                endpoint: http://partner.eucalyptus.com:8773/services
           provider_name: Eucalyptus
           account_label: ACCOUNT_LOGIN_ID
            api_id_label: QUERY_ID
        api_secret_label: SECRET_KEY
         x509_cert_label: X509_CERTIFICATE
          x509_key_label: X509_PRIVATE_KEY
        storage_delegate: NULL
        storage_endpoint: NULL
   storage_account_label: NULL
    storage_api_id_label: NULL
storage_api_secret_label: NULL
 storage_x509_cert_label: NULL
  storage_x509_key_label: NULL
           key_info_text: NULL
       provider_logo_url: /clouds/eucalyptus.png
     provider_status_url: NULL
        provider_web_url: NULL
        cloud_identifier: 14
